version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "simple-github/build.gradle" }}
      - run:
          name: Install Build tools 27.0.2
          command: sdkmanager "build-tools;27.0.2"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "simple-github/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
